name: Postman collection workflow

on:
 push
  branches:[main]
 workflow_dispatch:
 schedule:
  -corn :30 02 * * *  #8am-IST
  -corn :00 14 * * *  #7.30pm every day
  -corn :00 06 * * 1-5 # 11.30 IST monday to friday
jobs:
 run-postman-tests:
  runs-on: ubuntu-latest

 steps: 
 
 - name: Checkout
  uses: actions/checkout@v4.2.2

  -name: install nodejs and npm
   uses: actions/setup-node@v3.9.1
   with:
    node-version: '22'

  -name: install newman and Html-extra globally
   run: |
    npm install -g newman
    npm install -g newman-reporter-htmlextra 

  
  
  
 
 
 
 
